version: '3'
services:
  webserver:
    image: "nginx:alpine"
    ports:
     - "80:80"
    volumes:
     - ./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro
    application:
      build: .
    database:
      image: "postgres:alpine"